name: Go Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: stable

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run: go test ./... -v --cover
